name=PCF8573
version=1.0.0
author=Ignacy110
maintainer=Ignacy110
sentence=Arduino library for PCF8573 RTC I2C module
paragraph=This library allows microcontroller to use PCF8573 rtc module with Power Fail Detector.
category=Communication
url=https://github.com/Ignacy110/PCF8573
architectures=*
